'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class Assunto

    <Display(Name:="Codigo do Assunto")>
    Public Property AssuntoID As Integer
    <Display(Name:="Assunto")>
    Public Property AssuntoInfo As String

    Public Overridable Property Alunos As ICollection(Of Aluno) = New HashSet(Of Aluno)

End Class
