'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class EscolaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=EscolaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Alunoes() As DbSet(Of Aluno)
    Public Overridable Property Assuntoes() As DbSet(Of Assunto)
    Public Overridable Property Departamentoes() As DbSet(Of Departamento)

End Class
